version = "1.0"

[main]
name = "AdGuard Home configuration"
help = "If any trouble or question, please refer to the admin documentation right below!"
services = ["__APP__"]

[main.options]
name = "Configure AdGuard Home options"

[main.options.expose_port_53]
ask = "Expose port 53 to the Internet?"
no = "false"
type = "boolean"
yes = "true"
help = "If so, anyone who knows your server's IP can make a DNS request to it. It may be used to perform amplification attacks: https://en.wikipedia.org/wiki/Denial-of-service_attack#Amplification Please read the admin doc to understand that setting and to secure your server using allowlist."

[main.options.dns_over_https]
ask = "Enable DNS-over-HTTPS/QUIC?"
no = "false"
type = "boolean"
yes = "true"
bind = "tls>enabled:__INSTALL_DIR__/AdGuardHome.yaml"
help = "If so, anyone who knows your adguard address can make a doh request to https://adguardomain.tld/dns-query  It also may be used to perform amplification attacks. Read the admin doc to secure your server using allowlist."

[main.extra]
name = "Extra tools"

[main.extra.new_password]
ask = "Set a new admin password"
type = "string"
help = "With this tool, you can easily change the password of your AdGuard Home. Just put the desired password in the text input."
