version = "1.0"

[main]
name = "AdguardHome configuration"
services = ["__APP__"]

[main.options.dns_over_https]
ask = "Enable DNS-over-HTTPS"
bind = "tls>enabled:__INSTALL_DIR__/AdGuardHome.yaml"
no = "false"
type = "boolean"
yes = "true"
