version = "1.0"

[main]
name = "AdguardHome configuration"
services = ["__APP__"]

        [main.options.dns_over_https]
        ask = "Enable DNS-over-HTTPS"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "allow_unencrypted_doh:__INSTALL_DIR__/AdGuardHome.yaml"
