packaging_format = 2

id = "adguardhome"
name = "AdGuard Home"
description.en = "Network-wide ads & trackers blocking DNS server"
description.fr = "Serveur DNS, bloqueur de publicités et trackers"

version = "0.107.27~ynh1"

maintainers = ["ddataa"]

[upstream]
license = "GPL-3.0"
website = "https://adguard.com/adguard-home.html"
admindoc = "https://github.com/AdguardTeam/AdGuardHome/wiki"
userdoc = "https://kb.adguard.com/en"
code = "https://github.com/AdguardTeam/AdGuardHome"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/adguard"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.dns_over_https]
    ask.en = "Should DNS-over-HTTPS be enabled? (If so, anyone who knows your adguard address can make a doh request to https://adguardomain.tld/dns-query)"
    type = "boolean"
    default = true

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.27/AdGuardHome_linux_arm64.tar.gz"
        arm64.sha256 = "d89d3a46fa0a6498f7a918fa7e0e25f92eaca11fb9829082ba9709ef9820bc3f"
        amd64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.27/AdGuardHome_linux_amd64.tar.gz"
        amd64.sha256 = "98d06ff05e012475c9f3abe748cfb4b1f1244b78c1f1370c84cfba449e738183"
        armhf.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.27/AdGuardHome_linux_armv7.tar.gz"
        armhf.sha256 = "cb9fecbe03894b729b5092db823cbd54ea6883d5bbc46cb2c7de89b5d572ce39"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^AdGuardHome_linux_amd64.tar.gz$"
        autoupdate.asset.arm64 = "^AdGuardHome_linux_arm64.tar.gz$"
        autoupdate.asset.armhf = "^AdGuardHome_linux_armv7.tar.gz$"

    [resources.ports]
    adguard.default = 53
    adguard.exposed = "Both"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/re:__DOMAIN__/dns-query"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages ="python3-bcrypt, python3-yaml"
