packaging_format = 2

description.en = "Network-wide ads & trackers blocking DNS server"
description.fr = "Serveur DNS, bloqueur de publicités et trackers"
id = "adguardhome"
name = "AdGuard Home"

version = "0.107.44~ynh3"

maintainers = [ "ddataa", "OniriCorpe" ]

[upstream]
admindoc = "https://github.com/AdguardTeam/AdGuardHome/wiki"
code = "https://github.com/AdguardTeam/AdGuardHome"
license = "GPL-3.0"
userdoc = "https://kb.adguard.com/en"
website = "https://adguard.com/adguard-home.html"

[integration]
architectures = "all"
disk = "50M"
ldap = false
multi_instance = false
ram.build = "50M"
ram.runtime = "50M"
sso = false
yunohost = ">= 11.2"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    default = "/adguard"
    type = "path"

    [install.init_main_permission]
    default = "visitors"
    type = "group"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.dns_over_https]
    ask.en = "Should DNS-over-HTTPS be enabled? (If so, anyone who knows your adguard address can make a doh request to https://adguardomain.tld/dns-query)"
    default = true
    type = "boolean"

[resources]
    [resources.sources.main]
    amd64.sha256 = "bd19f93c47a8a893639e4ef28161e161708767c898cc10471ff3fefbc35a3a76"
    amd64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.44/AdGuardHome_linux_amd64.tar.gz"
    arm64.sha256 = "98b5a0c0645b6622dd638aaa818a8d7a3ac30cc8fbfa42aba7de36f20971d34e"
    arm64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.44/AdGuardHome_linux_arm64.tar.gz"
    armhf.sha256 = "49bf8be6745f18610daa5c0d9c71217b3699b451eeac3b1747b77b810600f835"
    armhf.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.44/AdGuardHome_linux_armv7.tar.gz"
    in_subdir = 2

    autoupdate.asset.amd64 = "^AdGuardHome_linux_amd64.tar.gz$"
    autoupdate.asset.arm64 = "^AdGuardHome_linux_arm64.tar.gz$"
    autoupdate.asset.armhf = "^AdGuardHome_linux_armv7.tar.gz$"
    autoupdate.strategy = "latest_github_release"

[resources.ports]
adguard.default = 53
adguard.exposed = "Both"

[resources.system_user]

[resources.install_dir]

[resources.permissions]
api.allowed = "visitors"
api.auth_header = true
api.protected = true
api.show_tile = false
api.url = "re:__DOMAIN__/control"
doh.allowed = "visitors"
doh.auth_header = false
doh.protected = true
doh.show_tile = false
doh.url = "re:__DOMAIN__/dns-query"
main.url = "/"

[resources.apt]
packages = "python3-bcrypt, python3-yaml"
