packaging_format = 2

description.en = "Network-wide ads & trackers blocking DNS server"
description.fr = "Serveur DNS, bloqueur de publicités et trackers"
id = "adguardhome"
name = "AdGuard Home"

version = "0.107.43~ynh4"

maintainers = ["ddataa", "OniriCorpe"]

[upstream]
admindoc = "https://github.com/AdguardTeam/AdGuardHome/wiki"
code = "https://github.com/AdguardTeam/AdGuardHome"
license = "GPL-3.0"
userdoc = "https://kb.adguard.com/en"
website = "https://adguard.com/adguard-home.html"

[integration]
architectures = "all"
disk = "50M"
ldap = false
multi_instance = false
ram.build = "200M"
ram.runtime = "200M"
sso = false
yunohost = ">= 11.2"

[install]
[install.domain]
type = "domain"

[install.path]
default = "/adguard"
type = "path"

[install.init_main_permission]
default = "all_users"
type = "group"
help.en = "Even by restricting access to users only, the AdGuard Home API will be available (ex. for a mobile app use)."

[install.admin]
type = "user"

[install.password]
type = "password"

[install.expose_port_53]
ask.en = "Expose port 53 to the Internet?"
help.en = "If so, anyone who knows your server's IP can make a DNS request to it. It may be used to perform amplification attacks: https://en.wikipedia.org/wiki/Denial-of-service_attack#Amplification"
default = false
type = "boolean"

[install.dns_over_https]
ask.en = "Should DNS-over-HTTPS/QUIC be enabled?"
help.en = "If so, anyone who knows your adguard address can make a doh request to https://adguardomain.tld/dns-query"
default = false
type = "boolean"

[resources]
[resources.sources.main]
amd64.sha256 = "0a4e3eec74ca56e2f29305445f5ac0596244fba6d3fe82164352d307b42496cf"
amd64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.43/AdGuardHome_linux_amd64.tar.gz"
arm64.sha256 = "c033985618c5eee3454702bb7f18dd697fc9eb13d7f688b3e468f204a8630e10"
arm64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.43/AdGuardHome_linux_arm64.tar.gz"
armhf.sha256 = "a33ec092fe33bfcd3540ea92aa4233b1a309dbc042fe68291ff54b5988fea649"
armhf.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.43/AdGuardHome_linux_armv7.tar.gz"
in_subdir = 2

autoupdate.asset.amd64 = "^AdGuardHome_linux_amd64.tar.gz$"
autoupdate.asset.arm64 = "^AdGuardHome_linux_arm64.tar.gz$"
autoupdate.asset.armhf = "^AdGuardHome_linux_armv7.tar.gz$"
autoupdate.strategy = "latest_github_release"

[resources.ports]
dns_over_http.default = 853
dns_over_http.exposed = "Both"
dns_over_quic.default = 784
dns_over_quic.exposed = "UDP"
internal_https.default = 13120
# AGH also uses port 53 but we can't put it here as dnsmasq uses it by default
# and the ynh core would assign us another port, however, on installation we
# edit dnsmasq's configuration to allow AGH to use port 53 on non-localhost IPs

[resources.system_user]

[resources.install_dir]

[resources.permissions]
api.allowed = "visitors"
api.auth_header = true
api.protected = true
api.show_tile = false
api.url = "re:__DOMAIN__/control"
doh.allowed = "visitors"
doh.auth_header = false
doh.protected = true
doh.show_tile = false
doh.url = "re:__DOMAIN__/dns-query"
main.url = "/"

[resources.apt]
packages = "python3-bcrypt, python3-yaml"
