packaging_format = 2

description.en = "Network-wide ads & trackers blocking DNS server"
description.fr = "Serveur DNS, bloqueur de publicités et trackers"
id = "adguardhome"
name = "AdGuard Home"

version = "0.107.46~ynh1"

maintainers = [ "ddataa", "OniriCorpe" ]

[upstream]
admindoc = "https://github.com/AdguardTeam/AdGuardHome/wiki"
code = "https://github.com/AdguardTeam/AdGuardHome"
license = "GPL-3.0"
userdoc = "https://kb.adguard.com/en"
website = "https://adguard.com/adguard-home.html"

[integration]
architectures = "all"
disk = "50M"
ldap = false
multi_instance = false
ram.build = "50M"
ram.runtime = "50M"
sso = false
yunohost = ">= 11.2"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    default = "/adguard"
    type = "path"

    [install.init_main_permission]
    default = "visitors"
    type = "group"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.dns_over_https]
    ask.en = "Should DNS-over-HTTPS be enabled? (If so, anyone who knows your adguard address can make a doh request to https://adguardomain.tld/dns-query)"
    default = true
    type = "boolean"

[resources]
    [resources.sources.main]
    amd64.sha256 = "8d31b2d0155285204d3561f49ad8f96186effb0fe215b304cc53ed1ffb2aabff"
    amd64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.46/AdGuardHome_linux_amd64.tar.gz"
    arm64.sha256 = "5011096bae383e27db9f0de063caeea9ec4b0e0bcac6728409d223dc51c8c0d0"
    arm64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.46/AdGuardHome_linux_arm64.tar.gz"
    armhf.sha256 = "5da33432de10845a06d1afb56b3d9043e29ab55e8d3f359e73bcda10d9af16ab"
    armhf.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.46/AdGuardHome_linux_armv7.tar.gz"
    in_subdir = 2

    autoupdate.asset.amd64 = "^AdGuardHome_linux_amd64.tar.gz$"
    autoupdate.asset.arm64 = "^AdGuardHome_linux_arm64.tar.gz$"
    autoupdate.asset.armhf = "^AdGuardHome_linux_armv7.tar.gz$"
    autoupdate.strategy = "latest_github_release"

[resources.ports]
adguard.default = 53
adguard.exposed = "Both"

[resources.system_user]

[resources.install_dir]

[resources.permissions]
api.allowed = "visitors"
api.auth_header = true
api.protected = true
api.show_tile = false
api.url = "re:__DOMAIN__/control"
doh.allowed = "visitors"
doh.auth_header = false
doh.protected = true
doh.show_tile = false
doh.url = "re:__DOMAIN__/dns-query"
main.url = "/"

[resources.apt]
packages = "python3-bcrypt, python3-yaml"
