packaging_format = 2

id = "adguardhome"
name = "AdGuard Home"
description.en = "Network-wide ads & trackers blocking DNS server"
description.fr = "Serveur DNS, bloqueur de publicités et trackers"

version = "0.107.41~ynh1"

maintainers = ["ddataa"]

[upstream]
license = "GPL-3.0"
website = "https://adguard.com/adguard-home.html"
admindoc = "https://github.com/AdguardTeam/AdGuardHome/wiki"
userdoc = "https://kb.adguard.com/en"
code = "https://github.com/AdguardTeam/AdGuardHome"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/adguard"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.dns_over_https]
    ask.en = "Should DNS-over-HTTPS be enabled? (If so, anyone who knows your adguard address can make a doh request to https://adguardomain.tld/dns-query)"
    type = "boolean"
    default = true

[resources]
        [resources.sources.main]
        in_subdir = "2"
        arm64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.41/AdGuardHome_linux_arm64.tar.gz"
        arm64.sha256 = "e23f5164a832c8647e0035b03189dc9c72821e9216ee5a5f8057739b8d072539"
        amd64.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.41/AdGuardHome_linux_amd64.tar.gz"
        amd64.sha256 = "9e171202103ff57bd4ddebc280cbc71eb7a33f5b1ba23170f462b3dfcdca93f5"
        armhf.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.41/AdGuardHome_linux_armv7.tar.gz"
        armhf.sha256 = "0ded3fcc63b009d7934730fd31e698b700153e6ac7dc205f5aa7352810a309d7"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^AdGuardHome_linux_amd64.tar.gz$"
        autoupdate.asset.arm64 = "^AdGuardHome_linux_arm64.tar.gz$"
        autoupdate.asset.armhf = "^AdGuardHome_linux_armv7.tar.gz$"

    [resources.ports]
    adguard.default = 53
    adguard.exposed = "Both"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/re:__DOMAIN__/dns-query"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages ="python3-bcrypt, python3-yaml"
