#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# PROCESS CLOSING PORTS
#=================================================
ynh_script_progression "Closing ports..."

# close ports
ynh_print_info "Closing port 53..."
ynh_hide_warnings yunohost firewall disallow Both 53
if [ "$dns_over_https" == "true" ]; then
    ynh_print_info "Closing DoH and DoQ ports..."
    ynh_hide_warnings yunohost firewall disallow Both "$port_dns_over_tls" --no-reload
    ynh_hide_warnings yunohost firewall disallow UDP "$port_dns_over_quic"
fi

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
ynh_script_progression "Removing $app service integration..."
yunohost service remove "$app"

ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated systemd config
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE VARIOUS FILES specific to the app...
#=================================================

# remove the kernel config file for DoQ
ynh_safe_rm "/etc/sysctl.d/10-adguardhome.conf"

# Remove the dedicated dnsmasq config for AdGuardHome
ynh_safe_rm "/etc/dnsmasq.d/$app"

systemctl restart dnsmasq

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
